# <b> ■ 판다스를 이용한 머신러닝 데이터 분석</b>
## <b> ■ 1장. 목차</b>
    1. 데이터 과학자가 판다스를 배우는 이유
    2. 판다스의 자료구조
    3. 인덱스 활용
    4. 산술 연산
    
### <b>■ 데이터 과학자가 판다스를 배우는 이유</b>
    1. 인공지능의 기름(원유)이 되는 것이 데이터인데 이 데이터를 수집하고 정리하는데 최적화된 도구
    2. 무료
    3. 가장 배우기 쉬운 언어인 파이썬을 기반으로 만들어짐
    
    예: 코로나 케글 데이터 분석 사례
    
### <b>■ 머신러닝 데이터 분석 5가지 단계</b>
    1. 데이터 수집과 설명 : Pandas
    2. 데이터 탐색 및 시각화 : Pandas, matplotlib, seaborn
    3. 머신러닝 모델 훈련 : sklearn 
    4. 머신러닝 모델 평가 : Pandas
    5. 머신러닝 모델 성능 개선 : Pandas (파생변수 생성)
    
## <b>■ 2. Pandas 자료구조</b>
    1. 판다스 시리즈(pandas Series)
    2. 판다스 데이터 프레임(pandas dataFrame)
    
### <b>■ Pandas의 Series에 대한 이해</b>
    시리즈(series)는 데이터가 순차적으로 나열된 1차원 배열의 형태를 갖는다. 파이썬 기본 내장 자료구조인 딕셔너리와 비슷한 구조를 갖고 있다.
    
        파이썬의 딕셔너리 자료구조 

            index0 ----> data0
            index1 ----> data1
            index2 ----> data2
            index3 ----> data3
               :           :
            indexN ----> dataN

        위와 같이 시리즈 또한 인덱스와 데이터의 값으로 구성되어 있다.

In [2]:
import pandas as pd
dict_data = {'a': 1, 'b': 2, 'c': 3}
sr = pd.Series(dict_data) # 딕셔너리를 시리즈로 변환
print(sr)
print(type(sr)) # type은 구조를 확인하는 함수

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

### ※ 문제1. 코로나 데이터 중 Case.csv를 pd.read_csv로 불러와서 case DataFrame으로 생성하고 city라는 컬럼의 type을 확인하시오

In [6]:
import pandas as pd
case = pd.read_csv('Case.csv')
print(type(case['city']))
print(type(case.city))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

### ※ 문제2. 코로나 case 데이터프레임의 모든 데이터를 다 출력하시오

In [8]:
import pandas as pd
case = pd.read_csv('Case.csv')
print(case)

      case_id          province             city  group  \
0     1000001             Seoul       Yongsan-gu   True
1     1000002             Seoul        Gwanak-gu   True
2     1000003             Seoul          Guro-gu   True
3     1000004             Seoul     Yangcheon-gu   True
4     1000005             Seoul        Dobong-gu   True
..        ...               ...              ...    ...
169   6100012  Gyeongsangnam-do                -  False
170   7000001           Jeju-do                -  False
171   7000002           Jeju-do                -  False
172   7000003           Jeju-do                -  False
173   7000004           Jeju-do  from other city   True

                  infection_case  confirmed   latitude   longitude
0                  Itaewon Clubs        139  37.538621  126.992652
1                        Richway        119   37.48208  126.901384
2            Guro-gu Call Center         95  37.508163  126.884387
3    Yangcheon Table Tennis Club         43  37.546061  126.874209
4                Day Care Center         43  37.679422  127.044374
..                           ...        ...        ...         ...
169                          etc         20          -           -
170              overseas inflow         14          -           -
171         contact with patient          0          -           -
172                          etc          4          -           -
173                Itaewon Clubs          1          -           -

[174 rows x 8 columns]

### ※ 문제3. 코로나 case 데이터프레임의 컬럼들이 뭐가 있는지 확인하시오

In [9]:
import pandas as pd
case = pd.read_csv('Case.csv')
print(case.columns)

Index([' case_id', 'province', 'city', 'group', 'infection_case', 'confirmed',
       'latitude', 'longitude'],
      dtype='object')

    컬럼소개
        case_id : case 식별번호
        province : 도시이름
        city : 지역구이름
        group : 집단 감염 여부
        infection_case : 감염 경로
        confirmed : 지역 내 누적 확진자 수

### ※ 문제4. 데이터프레임을 print해서 볼 때 아래와 같이 컬럼이 전부 출력되지 않고 중간에 ... 으로 나오면서 생략하는데 생략하지 않고 다 나오게 하려면 어떻게 해야하는가?

In [11]:
import pandas as pd
case = pd.read_csv('Case.csv')
pd.set_option('display.max_columns',100)
pd.set_option('display.max_rows',200)
print(case)

      case_id           province             city  group  \
0     1000001              Seoul       Yongsan-gu   True
1     1000002              Seoul        Gwanak-gu   True
2     1000003              Seoul          Guro-gu   True
3     1000004              Seoul     Yangcheon-gu   True
4     1000005              Seoul        Dobong-gu   True
5     1000006              Seoul          Guro-gu   True
6     1000007              Seoul  from other city   True
7     1000008              Seoul    Dongdaemun-gu   True
8     1000009              Seoul  from other city   True
9     1000010              Seoul        Gwanak-gu   True
10    1000011              Seoul     Eunpyeong-gu   True
11    1000012              Seoul     Seongdong-gu   True
12    1000013              Seoul        Jongno-gu   True
13    1000014              Seoul       Gangnam-gu   True
14    1000015              Seoul          Jung-gu   True
15    1000016              Seoul     Seodaemun-gu   True
16    1000017              Seoul        Jongno-gu   True
17    1000018              Seoul       Gangnam-gu   True
18    1000019              Seoul  from other city   True
19    1000020              Seoul     Geumcheon-gu   True
20    1000021              Seoul  from other city   True
21    1000022              Seoul  from other city   True
22    1000023              Seoul          Jung-gu   True
23    1000024              Seoul  Yeongdeungpo-gu   True
24    1000025              Seoul       Gangnam-gu   True
25    1000026              Seoul     Yangcheon-gu   True
26    1000027              Seoul        Seocho-gu   True
27    1000028              Seoul  from other city   True
28    1000029              Seoul       Gangnam-gu   True
29    1000030              Seoul       Gangseo-gu   True
30    1000031              Seoul  from other city   True
31    1000032              Seoul          Jung-gu   True
32    1000033              Seoul  from other city   True
33    1000034              Seoul                -   True
34    1000035              Seoul          Guro-gu   True
35    1000036              Seoul                -  False
36    1000037              Seoul                -  False
37    1000038              Seoul                -  False
38    1100001              Busan       Dongnae-gu   True
39    1100002              Busan  from other city   True
40    1100003              Busan       Suyeong-gu   True
41    1100004              Busan      Haeundae-gu   True
42    1100005              Busan           Jin-gu   True
43    1100006              Busan  from other city   True
44    1100007              Busan  from other city   True
45    1100008              Busan                -  False
46    1100009              Busan                -  False
47    1100010              Busan                -  False
48    1200001              Daegu           Nam-gu   True
49    1200002              Daegu     Dalseong-gun   True
50    1200003              Daegu           Seo-gu   True
51    1200004              Daegu     Dalseong-gun   True
52    1200005              Daegu          Dong-gu   True
53    1200006              Daegu  from other city   True
54    1200007              Daegu  from other city   True
55    1200008              Daegu                -  False
56    1200009              Daegu                -  False
57    1200010              Daegu                -  False
58    1300001            Gwangju          Dong-gu   True
59    1300002            Gwangju  from other city   True
60    1300003            Gwangju                -  False
61    1300004            Gwangju                -  False
62    1300005            Gwangju                -  False
63    1400001            Incheon  from other city   True
64    1400002            Incheon  from other city   True
65    1400003            Incheon  from other city   True
66    1400004            Incheon  from other city   True
67    1400005            Incheon                -  False
68    1400006            Incheon                -  False
69    1400007            Incheon                -  False
70    1500001            Daejeon                -   True
71    1500002            Daejeon           Seo-gu   True
72    1500003            Daejeon           Seo-gu   True
73    1500004            Daejeon           Seo-gu   True
74    1500005            Daejeon           Seo-gu   True
75    1500006            Daejeon  from other city   True
76    1500007            Daejeon  from other city   True
77    1500008            Daejeon                -  False
78    1500009            Daejeon                -  False
79    1500010            Daejeon                -  False
80    1600001              Ulsan  from other city   True
81    1600002              Ulsan                -  False
82    1600003              Ulsan                -  False
83    1600004              Ulsan                -  False
84    1700001             Sejong           Sejong   True
85    1700002             Sejong           Sejong   True
86    1700003             Sejong  from other city   True
87    1700004             Sejong                -  False
88    1700005             Sejong                -  False
89    1700006             Sejong                -  False
90    2000001        Gyeonggi-do      Seongnam-si   True
91    2000002        Gyeonggi-do       Bucheon-si   True
92    2000003        Gyeonggi-do  from other city   True
93    2000004        Gyeonggi-do  from other city   True
94    2000005        Gyeonggi-do     Uijeongbu-si   True
95    2000006        Gyeonggi-do  from other city   True
96    2000007        Gyeonggi-do  from other city   True
97    2000008        Gyeonggi-do  from other city   True
98    2000009        Gyeonggi-do                -   True
99    2000010        Gyeonggi-do      Seongnam-si   True
100   2000011        Gyeonggi-do        Anyang-si   True
101   2000012        Gyeonggi-do         Suwon-si   True
102   2000013        Gyeonggi-do        Anyang-si   True
103   2000014        Gyeonggi-do         Suwon-si   True
104   2000015        Gyeonggi-do  from other city   True
105   2000016        Gyeonggi-do  from other city   True
106   2000017        Gyeonggi-do  from other city   True
107   2000018        Gyeonggi-do  from other city   True
108   2000019        Gyeonggi-do      Seongnam-si   True
109   2000020        Gyeonggi-do                -  False
110   2000021        Gyeonggi-do                -  False
111   2000022        Gyeonggi-do                -  False
112   3000001         Gangwon-do  from other city   True
113   3000002         Gangwon-do  from other city   True
114   3000003         Gangwon-do         Wonju-si   True
115   3000004         Gangwon-do  from other city   True
116   3000005         Gangwon-do  from other city   True
117   3000006         Gangwon-do                -  False
118   3000007         Gangwon-do                -  False
119   3000008         Gangwon-do                -  False
120   4000001  Chungcheongbuk-do       Goesan-gun   True
121   4000002  Chungcheongbuk-do  from other city   True
122   4000003  Chungcheongbuk-do  from other city   True
123   4000004  Chungcheongbuk-do  from other city   True
124   4000005  Chungcheongbuk-do                -  False
125   4000006  Chungcheongbuk-do                -  False
126   4000007  Chungcheongbuk-do                -  False
127   4100001  Chungcheongnam-do       Cheonan-si   True
128   4100002  Chungcheongnam-do  from other city   True
129   4100003  Chungcheongnam-do        Seosan-si   True
130   4100004  Chungcheongnam-do  from other city   True
131   4100005  Chungcheongnam-do  from other city   True
132   4100006  Chungcheongnam-do                -  False
133   4100007  Chungcheongnam-do                -  False
134   4100008  Chungcheongnam-do                -  False
135   5000001       Jeollabuk-do  from other city   True
136   5000002       Jeollabuk-do  from other city   True
137   5000003       Jeollabuk-do  from other city   True
138   5000004       Jeollabuk-do                -  False
139   5000005       Jeollabuk-do                -  False
140   5100001       Jeollanam-do         Muan-gun   True
141   5100002       Jeollanam-do  from other city   True
142   5100003       Jeollanam-do                -  False
143   5100004       Jeollanam-do                -  False
144   5100005       Jeollanam-do                -  False
145   6000001   Gyeongsangbuk-do  from other city   True
146   6000002   Gyeongsangbuk-do     Cheongdo-gun   True
147   6000003   Gyeongsangbuk-do      Bonghwa-gun   True
148   6000004   Gyeongsangbuk-do     Gyeongsan-si   True
149   6000005   Gyeongsangbuk-do  from other city   True
150   6000006   Gyeongsangbuk-do       Yechun-gun   True
151   6000007   Gyeongsangbuk-do      Chilgok-gun   True
152   6000008   Gyeongsangbuk-do     Gyeongsan-si   True
153   6000009   Gyeongsangbuk-do     Gyeongsan-si   True
154   6000010   Gyeongsangbuk-do          Gumi-si   True
155   6000011   Gyeongsangbuk-do                -  False
156   6000012   Gyeongsangbuk-do                -  False
157   6000013   Gyeongsangbuk-do                -  False
158   6100001   Gyeongsangnam-do  from other city   True
159   6100002   Gyeongsangnam-do     Geochang-gun   True
160   6100003   Gyeongsangnam-do         Jinju-si   True
161   6100004   Gyeongsangnam-do     Geochang-gun   True
162   6100005   Gyeongsangnam-do      Changwon-si   True
163   6100006   Gyeongsangnam-do  Changnyeong-gun   True
164   6100007   Gyeongsangnam-do       Yangsan-si   True
165   6100008   Gyeongsangnam-do  from other city   True
166   6100009   Gyeongsangnam-do  from other city   True
167   6100010   Gyeongsangnam-do                -  False
168   6100011   Gyeongsangnam-do                -  False
169   6100012   Gyeongsangnam-do                -  False
170   7000001            Jeju-do                -  False
171   7000002            Jeju-do                -  False
172   7000003            Jeju-do                -  False
173   7000004            Jeju-do  from other city   True

                                    infection_case  confirmed    latitude  \
0                                    Itaewon Clubs        139   37.538621
1                                          Richway        119    37.48208
2                              Guro-gu Call Center         95   37.508163
3                      Yangcheon Table Tennis Club         43   37.546061
4                                  Day Care Center         43   37.679422
5                            Manmin Central Church         41   37.481059
6                 SMR Newly Planted Churches Group         36           -
7                                    Dongan Church         17   37.592888
8                         Coupang Logistics Center         25           -
9                                  Wangsung Church         30   37.481735
10                   Eunpyeong St. Mary's Hospital         14    37.63369
11                                Seongdong-gu APT         13    37.55713
12                         Jongno Community Center         10    37.57681
13                          Samsung Medical Center          7    37.48825
14                         Jung-gu Fashion Company          7   37.562405
15                              Yeonana News Class          5   37.558147
16                  Korea Campus Crusade of Christ          7   37.594782
17                  Gangnam Yeoksam-dong gathering          6           -
18                      Daejeon door-to-door sales          1           -
19   Geumcheon-gu rice milling machine manufacture          6           -
20                              Shincheonji Church          8           -
21                       Guri Collective Infection          5           -
22                               KB Life Insurance         13   37.560899
23                 Yeongdeungpo Learning Institute          3   37.520846
24                           Gangnam Dongin Church          1   37.522331
25                 Biblical Language study meeting          3   37.524623
26                                   Seocho Family          5           -
27                      Anyang Gunpo Pastors Group          1           -
28                 Samsung Fire & Marine Insurance          4   37.498279
29                       SJ Investment Call Center          0   37.559649
30                                 Yongin Brothers          4           -
31           Seoul City Hall Station safety worker          3   37.565699
32                         Uiwang Logistics Center          2           -
33                                     Orange Life          1           -
34                                 Daezayeon Korea          3   37.486837
35                                 overseas inflow        298           -
36                            contact with patient        162           -
37                                             etc        100           -
38                                   Onchun Church         39    35.21628
39                              Shincheonji Church         12           -
40                         Suyeong-gu Kindergarten          5    35.16708
41                     Haeundae-gu Catholic Church          6    35.20599
42                                  Jin-gu Academy          4    35.17371
43                                   Itaewon Clubs          4           -
44                        Cheongdo Daenam Hospital          1           -
45                                 overseas inflow         36           -
46                            contact with patient         19           -
47                                             etc         30           -
48                              Shincheonji Church       4511    35.84008
49                           Second Mi-Ju Hospital        196   35.857375
50                 Hansarang Convalescent Hospital        124   35.885592
51                    Daesil Convalescent Hospital        101   35.857393
52                                 Fatima Hospital         39    35.88395
53                                   Itaewon Clubs          2           -
54                        Cheongdo Daenam Hospital          2           -
55                                 overseas inflow         41           -
56                            contact with patient        917           -
57                                             etc        747           -
58                              Gwangneuksa Temple          5   35.136035
59                              Shincheonji Church          9           -
60                                 overseas inflow         23           -
61                            contact with patient          5           -
62                                             etc          1           -
63                                   Itaewon Clubs         53           -
64                        Coupang Logistics Center         42           -
65                             Guro-gu Call Center         20           -
66                              Shincheonji Church          2           -
67                                 overseas inflow         68           -
68                            contact with patient          6           -
69                                             etc         11           -
70                   Door-to-door sales in Daejeon         55           -
71                         Dunsan Electronics Town         13  36.3400973
72                                     Orange Town          7  36.3398739
73                                 Dreaming Church          4   36.346869
74                 Korea Forest Engineer Institute          3   36.358123
75                              Shincheonji Church          2           -
76                            Seosan-si Laboratory          2           -
77                                 overseas inflow         15           -
78                            contact with patient         15           -
79                                             etc         15           -
80                              Shincheonji Church         16           -
81                                 overseas inflow         25           -
82                            contact with patient          3           -
83                                             etc          7           -
84                Ministry of Oceans and Fisheries         31   36.504713
85                          gym facility in Sejong          8    36.48025
86                              Shincheonji Church          1           -
87                                 overseas inflow          5           -
88                            contact with patient          3           -
89                                             etc          1           -
90                 River of Grace Community Church         67   37.455687
91                        Coupang Logistics Center         67   37.530579
92                                   Itaewon Clubs         59           -
93                                         Richway         58           -
94                   Uijeongbu St. Mary’s Hospital         50   37.758635
95                             Guro-gu Call Center         50           -
96                              Shincheonji Church         29           -
97                     Yangcheon Table Tennis Club         28           -
98                SMR Newly Planted Churches Group         25           -
99                        Bundang Jesaeng Hospital         22    37.38833
100                     Anyang Gunpo Pastors Group         22   37.381784
101           Lotte Confectionery logistics center         15   37.287356
102                              Lord Glory Church         17   37.403722
103                 Suwon Saeng Myeong Saem Church         10     37.2376
104                 Korea Campus Crusade of Christ          7           -
105  Geumcheon-gu rice milling machine manufacture          6           -
106                                Wangsung Church          6           -
107          Seoul City Hall Station safety worker          5           -
108                   Seongnam neighbors gathering          5           -
109                                overseas inflow        305           -
110                           contact with patient         63           -
111                                            etc         84           -
112                             Shincheonji Church         17           -
113                  Uijeongbu St. Mary’s Hospital         10           -
114                            Wonju-si Apartments          4   37.342762
115                                        Richway          4           -
116  Geumcheon-gu rice milling machine manufacture          4           -
117                                overseas inflow         16           -
118                           contact with patient          0           -
119                                            etc          7           -
120                      Goesan-gun Jangyeon-myeon         11    36.82422
121                                  Itaewon Clubs          9           -
122                            Guro-gu Call Center          2           -
123                             Shincheonji Church          6           -
124                                overseas inflow         13           -
125                           contact with patient          8           -
126                                            etc         11           -
127                        gym facility in Cheonan        103    36.81503
128                  Door-to-door sales in Daejeon         10           -
129                           Seosan-si Laboratory          9   37.000354
130                                        Richway          3           -
131              Eunpyeong-Boksagol culture center          3           -
132                                overseas inflow         16           -
133                           contact with patient          2           -

### ※ 문제5. emp3.csv를 불러와서 emp 데이터프레임으로 만들고 emp 테이블 전체를 출력하는데 모든 컬럼이 다 나오게 하시오

In [13]:
import pandas as pd
emp = pd.read_csv('emp3.csv')
print(emp)

    index  empno   ename        job     mgr         hiredate   sal    comm  \
0       1   7839    KING  PRESIDENT     NaN  1981-11-17 0:00  5000     NaN
1       2   7698   BLAKE    MANAGER  7839.0  1981-05-01 0:00  2850     NaN
2       3   7782   CLARK    MANAGER  7839.0  1981-05-09 0:00  2450     NaN
3       4   7566   JONES    MANAGER  7839.0  1981-04-01 0:00  2975     NaN
4       5   7654  MARTIN   SALESMAN  7698.0  1981-09-10 0:00  1250  1400.0
5       6   7499   ALLEN   SALESMAN  7698.0  1981-02-11 0:00  1600   300.0
6       7   7844  TURNER   SALESMAN  7698.0  1981-08-21 0:00  1500     0.0
7       8   7900   JAMES      CLERK  7698.0  1981-12-11 0:00   950     NaN
8       9   7521    WARD   SALESMAN  7698.0  1981-02-23 0:00  1250   500.0
9      10   7902    FORD    ANALYST  7566.0  1981-12-11 0:00  3000     NaN
10     11   7369   SMITH      CLERK  7902.0  1980-12-09 0:00   800     NaN
11     12   7788   SCOTT    ANALYST  7566.0  1982-12-22 0:00  3000     NaN
12     13   7876   ADAMS      CLERK  7788.0  1983-01-15 0:00  1100     NaN
13     14   7934  MILLER      CLERK  7782.0  1982-01-11 0:00  1300     NaN

    deptno
0       10
1       30
2       10
3       20
4       30
5       30
6       30
7       30
8       30
9       20
10      20
11      20
12      20
13      10

### <b>■ 2.2 Pandas series의 index와 values</b>
    시리즈 클래스의 index 속성을 이용하여 인덱스 배열만 따로 선택할 수 있다.
        문법 : Series객체.index
    
    시리즈 클래스의 values 속성을 이용하여 값 배열만 따로 선택할 수 있다.
        문법 : Series객체.values

In [15]:
# 예제
import pandas as pd
list_data = ['a', 'b', 'c', 'd']
sr = pd.Series(list_data)
print(sr)
print(sr.index)
print(sr.values)

0    a
1    b
2    c
3    d
dtype: object
RangeIndex(start=0, stop=4, step=1)
['a' 'b' 'c' 'd']

### ※ 문제6. 코로나 데이터  Case 데이터프레임에서 누적 확진자수를 나타내는 confirmed의 값들을 비어있는 리스트인 cf_num에 담으시오

In [18]:
import pandas as pd
case = pd.read_csv('Case.csv')
cf_num = list(case['confirmed'])
cf_num

[139,
 119,
 95,
 43,
 43,
 41,
 36,
 17,
 25,
 30,
 14,
 13,
 10,
 7,
 7,
 5,
 7,
 6,
 1,
 6,
 8,
 5,
 13,
 3,
 1,
 3,
 5,
 1,
 4,
 0,
 4,
 3,
 2,
 1,
 3,
 298,
 162,
 100,
 39,
 12,
 5,
 6,
 4,
 4,
 1,
 36,
 19,
 30,
 4511,
 196,
 124,
 101,
 39,
 2,
 2,
 41,
 917,
 747,
 5,
 9,
 23,
 5,
 1,
 53,
 42,
 20,
 2,
 68,
 6,
 11,
 55,
 13,
 7,
 4,
 3,
 2,
 2,
 15,
 15,
 15,
 16,
 25,
 3,
 7,
 31,
 8,
 1,
 5,
 3,
 1,
 67,
 67,
 59,
 58,
 50,
 50,
 29,
 28,
 25,
 22,
 22,
 15,
 17,
 10,
 7,
 6,
 6,
 5,
 5,
 305,
 63,
 84,
 17,
 10,
 4,
 4,
 4,
 16,
 0,
 7,
 11,
 9,
 2,
 6,
 13,
 8,
 11,
 103,
 10,
 9,
 3,
 3,
 16,
 2,
 12,
 2,
 3,
 1,
 12,
 5,
 2,
 1,
 14,
 4,
 4,
 566,
 119,
 68,
 66,
 41,
 40,
 36,
 17,
 16,
 10,
 22,
 190,
 133,
 32,
 10,
 9,
 8,
 7,
 7,
 3,
 2,
 2,
 26,
 6,
 20,
 14,
 0,
 4,
 1]

### 문제7. 누적 확진자수의 평균값을 출력하시오

In [22]:
import numpy as np
print(sum(cf_num)/len(cf_num))
print(np.mean(cf_num))

65.48850574712644
65.48850574712644

### <b>■ 2.3 series의 원소 선택</b>
    원소의 위치를 나타내는 주소 역할을 하는 인덱스를 이용하여 시리즈의 원소를 선택할 수 있다.
    하나의 원소를 선택할 수 있고 여러개의 원소를 선택할 수도 있다.

In [23]:
# 예제
tup_data = ('영인', '2020-01-28', '여', True)
sr = pd.Series(tup_data, index=['이름', '생년월일', '성별', '학생여부'])
sr

이름              영인
생년월일    2020-01-28
성별               여
학생여부          True
dtype: object